Repository roastduck/FreeTensor, pull requests merged in 2022-07, with the labels that each got.

#133 Display link to each section in the document
  mkdocs.yml
Labels: documentation

#134 Minor improvement on document
  docs/guide/build-and-run.md
Labels: documentation

#132 An OpenMP wrapper to handle exceptions from each thread
  include/math/utils.h
  include/omp_utils.h
  include/ref.h
  include/sub_tree.h
  src/analyze/deps.cc
  src/auto_schedule/auto_schedule.cc
Labels: enhancement

#142 Refactor ostream overloading
  include/codegen/code_gen.h
  include/debug.h
  include/lower.h
  include/math/presburger.h
  include/serialize/print_ast.h
  src/analyze/deps.cc
  src/analyze/find_elementwise.cc
  src/auto_schedule/auto_schedule.cc
  src/codegen/detail/code_gen.h
  src/schedule.cc
  src/serialize/print_ast.cc
Labels: enhancement

#143 Refactor ostream overloading (2)
  ffi/tensor_types.cc
  include/analyze/deps.h
  include/ast.h
  include/buffer.h
  include/data_type.h
  include/debug.h
  include/frontend/frontend_var.h
  include/math/presburger.h
  include/parallel_scope.h
  include/serialize/to_string.h
  src/analyze/deps.cc
  src/ast.cc
Labels: enhancement

#145 Memorize and reuse identical scheduling decisions
  ffi/schedule.cc
  include/allocator.h
  include/auto_schedule/sketch.h
  include/container_utils.h
  include/except.h
  include/hash.h
  include/lazy.h
  include/schedule.h
  include/schedule/fission.h
  include/schedule/memoized_schedules.h
  include/schedule/schedule_log.h
  include/serialize/to_string.h
  include/shared_linked_list.h
  src/auto_schedule/auto_schedule.cc
  src/auto_schedule/sketch.cc
  src/except.cc
  src/schedule.cc
  test/30.schedule/test_auto_fuse.py
  test/30.schedule/test_auto_parallelize.py
  test/30.schedule/test_memoized_schedules.py
  test/80.auto_schedule/test_multi_level_tiling_with_fusion.py
  test/80.auto_schedule/test_parallelize_rule.py
  test/80.auto_schedule/test_thread_bind.py
  test/80.auto_schedule/test_unroll_rule.py
Labels: enhancement

#146 [WIP] Fix serialization/deserialization for left-association issues.
  grammar/ast_parser.g
  grammar/pb_parser.g
  include/serialize/print_ast.h
  src/serialize/print_ast.cc
  test/00.hello_world/test_serialize_ast.py
Labels: bug

#150 Basis of the new auto scheduling based on Bayesian statistics
  ffi/schedule.cc
  include/func_utils.h
  include/probability/rand_ctx.h
  include/probability/rand_var.h
  include/ref.h
  include/schedule.h
  include/shared_linked_list.h
  src/probability/rand_ctx.cc
  src/probability/rand_var.cc
  src/schedule.cc
  test/30.schedule/test_auto_fuse.py
Labels: enhancement

#151 Fix debug info and indentation handling in staging framework.
  python/freetensor/core/staging.py
  test/50.frontend/test_error_report.py
Labels: bug

#152 Fix integer overflow in analyze/comp_unique_bounds
  include/analyze/comp_unique_bounds.h
  runtime/gpu_runtime.h
  src/analyze/comp_unique_bounds.cc
  src/pass/simplify.cc
  test/20.pass/test_simplify.py
  test/40.codegen/gpu/test_gpu.py
Labels: bug

#153 Helper function in FindDeps to only analyze a sub-AST
  include/analyze/deps.h
  src/analyze/find_multi_level_tiling.cc
  src/schedule/blend.cc
  src/schedule/parallelize.cc
  src/schedule/reorder.cc
  src/schedule/vectorize.cc
Labels: enhancement

#154 Conditional random variables in the new auto scheduling
  include/analyze/deps.h
  include/probability/rand_cond.h
  include/probability/rand_ctx.h
  include/probability/rand_var.h
  include/shared_linked_list.h
  src/analyze/deps.cc
  src/probability/rand_ctx.cc
  src/probability/rand_var.cc
  src/schedule.cc
  test/30.schedule/test_auto_fuse.py
Labels: enhancement

#159 Target / Device [De]Serialization
  ffi/device.cc
  include/serialize/print_driver.h
  python/freetensor/core/__init__.py
  python/freetensor/core/driver.py
  python/freetensor/core/serialize.py
  test/00.hello_world/test_serialize_driver.py
Labels: enhancement

#164 Fix pass/make_heap_alloc
  include/pass/make_heap_alloc.h
  src/debug/match_ast.cc
  src/pass/make_heap_alloc.cc
  test/20.pass/test_make_heap_alloc.py
  test/20.pass/test_remove_writes.py
  test/21.autograd/test_grad.py
  test/40.codegen/gpu/test_gpu_sync.py
Labels: bug

#165 Fix pass/shrink_var
  include/math/bounds.h
  include/pass/shrink_var.h
  src/pass/shrink_var.cc
  src/pass/z3_simplify.cc
  test/20.pass/test_shrink_var.py
Labels: bug

#166 Fix doc broken in #161
  docs/guide/build-and-run.md
Labels: documentation

#167 Fix CheckLoopOrder utility
  include/schedule/check_loop_order.h
  src/schedule/check_loop_order.cc
Labels: bug

#170 Fix analyze/deps for negative steps in loops
  include/analyze/deps.h
  include/pass/const_fold.h
  src/analyze/deps.cc
  src/pass/prop_one_time_use.cc
  src/pass/remove_writes.cc
  src/pass/tensor_prop_const.cc
  src/schedule/inlining.cc
  test/30.schedule/test_fission.py
Labels: bug
