Repository roastduck/FreeTensor, pull requests merged in 2023-01, with the labels that each got.

#324 Fix runtime debug helper GPUScalar
  runtime/gpu_runtime.h
  src/codegen/code_gen_cuda.cc
  src/except.cc
Labels: bug

#328 Change the API to retrieve result ASTs from a Schedule log
  ffi/func.cc
  ffi/schedule.cc
  include/schedule/schedule_log.h
  test/30.schedule/test_auto_fission_fuse.py
  test/30.schedule/test_auto_parallelize.py
  test/30.schedule/test_auto_reorder.py
  test/30.schedule/test_auto_set_mem_type.py
  test/30.schedule/test_auto_use_lib.py
  test/80.auto_schedule/test_multi_level_tiling_with_fusion.py
  test/80.auto_schedule/test_parallelize_rule.py
  test/80.auto_schedule/test_thread_bind.py
  test/80.auto_schedule/test_unroll_rule.py
Labels: enhancement, productivity

#329 Fix name conflicts in pass/gpu/normalize_var_in_kernel
  include/pass/gpu/normalize_var_in_kernel.h
  src/pass/gpu/normalize_var_in_kernel.cc
Labels: bug

#330 Improve atomic reduction
  include/pass/make_parallel_reduction.h
  src/codegen/code_gen_cpu.cc
  src/pass/make_parallel_reduction.cc
  test/40.codegen/cpu/test_cpu_reduce.py
Labels: enhancement, target performance

#331 Fix debugging with DEBUG_CUDA_WITH_UM
  docs/guide/build-and-run.md
  ffi/config.cc
  include/config.h
  src/codegen/code_gen_cuda.cc
Labels: bug

#332 Fix AST parser on non-atomic ReduceTo.
  grammar/ast_parser.g
Labels: bug

#333 Fix autograd when an index is taped
  src/autograd/grad.cc
  test/21.autograd/test_grad.py
Labels: bug

#336 Fix atomic reduction
  src/pass/make_parallel_reduction.cc
  src/pass/merge_and_hoist_if.cc
  test/40.codegen/cpu/test_cpu_reduce.py
Labels: bug

#337 [CUDA] Fix inserting thread synchronization in branches
  src/pass/gpu/make_sync.cc
  test/40.codegen/gpu/test_gpu_sync.py
Labels: bug

#338 Fix ID conflict in pass/remove_writes
  include/debug/check_conflict_id.h
  include/pass/remove_writes.h
Labels: bug

#339 [CUDA] Fix finding whether a node is in an "else" in pass/gpu/make_sync
  include/pass/gpu/make_sync.h
  src/pass/gpu/make_sync.cc
Labels: bug

#340 Consider gpu/local capacity in auto_set_mem_type
  src/schedule/auto_set_mem_type.cc
  test/30.schedule/test_auto_set_mem_type.py
Labels: enhancement, target performance

#341 Optionally reject indirect access in schedule/set_mem_type
  ffi/schedule.cc
  include/schedule.h
  include/schedule/set_mem_type.h
  python/freetensor/core/schedule.py
  src/schedule/set_mem_type.cc
  test/30.schedule/test_auto_set_mem_type.py
  test/30.schedule/test_set_mem_type.py
Labels: enhancement, functionality

#342 [CUDA] No need to synchronize between atomic reductions
  src/pass/gpu/make_sync.cc
  test/40.codegen/gpu/test_gpu_sync.py
Labels: enhancement, target performance
