Repository roastduck/FreeTensor, pull requests merged in 2023-07, with the labels that each got.

#510 [CUDA] Fix the shape of the workspace used by parallel reduction
  include/for_property.h
  include/pass/gpu/lower_parallel_reduction.h
  src/analyze/comp_access_bound.cc
  src/pass/gpu/lower_parallel_reduction.cc
  test/40.codegen/gpu/test_gpu_reduce.py
Labels: bug

#513 Don't call filters if already filtered out by DepType
  include/analyze/deps.h
  src/analyze/deps.cc
Labels: bug, compiler performance

#514 Remove some unnecessary reorder from auto_parallelize
  src/schedule/auto_parallelize.cc
Labels: enhancement, target performance

#511 Remove redundancy in Pluto.
  include/disjoint_set.h
  src/analyze/deps.cc
  src/schedule/pluto.cc
Labels: enhancement, compiler performance

#515 Use `y` for `y = a / b`'s gradient
  include/pass/remove_dead_var.h
  src/autograd/derivative.cc
  src/pass/remove_dead_var.cc
Labels: bug, target performance

#517 Do trivial inversion from `y` to use in derivatives
  include/autograd/derivative.h
  include/autograd/invert_from_store.h
  include/autograd/replace_by_saved.h
  src/autograd/derivative.cc
  src/autograd/grad.cc
  src/autograd/invert_from_store.cc
  src/autograd/replace_by_saved.cc
  src/autograd/tape_strategy.cc
  test/21.autograd/test_grad.py
Labels: enhancement, target performance

#518 Revert #268 and re-implement constraints on external variables
  include/analyze/deps.h
  include/lower.h
  src/analyze/deps.cc
  src/autograd/grad.cc
  src/pass/remove_writes.cc
  src/schedule/pluto.cc
  test/21.autograd/test_output_intermediates.py
Labels: bug

#520 Set reset_provided_grad=False in jacrev
  python/freetensor/core/autograd.py
Labels: enhancement, target performance

#521 [AD] Fix inverting expressions
  src/autograd/derivative.cc
  test/21.autograd/test_grad.py
Labels: bug

#524 Improve `schedule/reorder` and `schedule/auto_reorder`
  ffi/schedule.cc
  include/schedule.h
  include/schedule/reorder.h
  python/freetensor/core/schedule.py
  src/schedule/auto_reorder.cc
  src/schedule/reorder.cc
  test/30.schedule/test_reorder.py
  test/31.auto_schedule/test_auto_fission_fuse.py
  test/31.auto_schedule/test_auto_parallelize.py
  test/31.auto_schedule/test_auto_reorder.py
  test/70.program/test_common_transforms.py
Labels: enhancement, target performance, functionality

#525 Pre-allocate static gpu/global stack at library loading time
  ffi/codegen.cc
  include/codegen/code_gen_cpu.h
  include/codegen/code_gen_cuda.h
  include/codegen/native_code.h
  python/freetensor/core/codegen.py
  python/freetensor/core/driver.py
  runtime/gpu_context.h
  runtime/gpu_runtime.h
  src/codegen/code_gen.cc
  src/codegen/code_gen_cpu.cc
  src/codegen/code_gen_cuda.cc
  src/codegen/native_code.cc
  src/driver.cc
  test/40.codegen/gpu/test_gpu.py
Labels: enhancement, target performance

#528 Add `schedule/auto_mem_layout`
  ffi/schedule.cc
  include/analyze/count_contig_access_loops.h
  include/schedule.h
  python/freetensor/core/schedule.py
  src/schedule.cc
  src/schedule/auto_mem_layout.cc
  src/schedule/cache.cc
  test/31.auto_schedule/test_auto_fission_fuse.py
  test/31.auto_schedule/test_auto_inline.py
  test/31.auto_schedule/test_auto_mem_layout.py
  test/31.auto_schedule/test_auto_parallelize.py
Labels: enhancement, target performance, functionality

#531 Fix libop/logsumexp when keepdims=True
  python/freetensor/libop/logsumexp.py
  test/60.libop/test_logsumexp.py
Labels: bug

#532 Use CUDA's memory pool
  include/codegen/native_code.h
  runtime/gpu_context.h
  runtime/gpu_runtime.h
  src/codegen/code_gen_cuda.cc
  src/driver.cc
  test/40.codegen/gpu/test_gpu.py
Labels: enhancement, target performance

#530 Add `mode` in `schedule/as_matmul`
  ffi/schedule.cc
  include/schedule.h
  include/schedule/as_matmul.h
  python/freetensor/core/schedule.py
  src/schedule/as_matmul.cc
  src/schedule/auto_use_lib.cc
Labels: enhancement, functionality

#533 Fix schedule/auto_set_mem_type for finding kernel root
  src/schedule/auto_set_mem_type.cc
Labels: bug

#535 [AD] Fix NoReuseOnly strategy
  src/autograd/all_no_reuse_defs.cc
Labels: bug

#538 Improvements on auto-scheduling speed
  ffi/pass.cc
  grammar/selector_lexer.g
  grammar/selector_parser.g
  include/pass/tensor_prop_const.h
  include/schedule/check_not_in_lib.h
  src/pass/tensor_prop_const.cc
  src/schedule/auto_unroll.cc
  src/schedule/blend.cc
  src/schedule/cache.cc
  src/schedule/fission.cc
  src/schedule/fuse.cc
  src/schedule/merge.cc
  src/schedule/parallelize.cc
  src/schedule/permute.cc
  src/schedule/pluto.cc
  src/schedule/reorder.cc
  src/schedule/split.cc
  src/schedule/swap.cc
  src/schedule/unroll.cc
  src/schedule/vectorize.cc
Labels: enhancement, compiler performance

#539 Fix auto_parallelize for multi-level nested loops
  src/schedule/auto_parallelize.cc
  test/31.auto_schedule/test_auto_parallelize.py
Labels: bug

#541 Refactor `schedule/auto_parallelize`
  include/schedule.h
  src/schedule/auto_parallelize.cc
  src/schedule/parallelize.cc
  src/schedule/split.cc
  test/31.auto_schedule/test_auto_parallelize.py
Labels: enhancement, compiler performance, target performance

#546 Minor fix on `schedule/as_matmul`
  src/schedule/as_matmul.cc
Labels: bug

#547 Enable #461 only for Clang
  include/driver.h
  src/codegen/code_gen_cpu.cc
Labels: enhancement, target performance

#548 Fix checking for nested CUDA scopes in schedule/parallelize
  include/analyze/find_loop_variance.h
  include/lazy.h
  src/analyze/find_loop_variance.cc
  src/schedule/parallelize.cc
  test/30.schedule/test_parallelize.py
  test/70.program/test_gpu_conv2d.py
Labels: bug

#549 Improve parallel reduction for CPU
  include/pass/cpu/lower_parallel_reduction.h
  src/codegen/code_gen_cpu.cc
  src/pass/cpu/lower_parallel_reduction.cc
  src/schedule/auto_parallelize.cc
  src/schedule/auto_reorder.cc
  test/40.codegen/cpu/test_cpu_reduce.py
Labels: enhancement, target performance

#551 Fix block crossing checking in `pass/gpu/make_sync`
  src/pass/gpu/make_sync.cc
  test/40.codegen/gpu/test_gpu_sync.py
Labels: bug

#553 More simplification rules
  src/pass/gpu/normalize_threads.cc
  src/pass/simplify.cc
  test/20.pass/test_shrink_var.py
  test/20.pass/test_simplify.py
  test/40.codegen/gpu/test_gpu.py
Labels: enhancement, target performance

#555 Add `checkNotModifiedFastPreCheck`
  include/analyze/check_not_modified.h
  src/analyze/check_not_modified.cc
  src/pass/prop_one_time_use.cc
  src/pass/remove_writes.cc
Labels: enhancement, compiler performance

#556 Don't propagate into statements already bound to MatMul
  src/pass/prop_one_time_use.cc
  src/pass/remove_writes.cc
  src/pass/tensor_prop_const.cc
  src/schedule/inlining.cc
Labels: bug

#560 Fix custom gradient when it is empty
  python/freetensor/core/stmt.py
  test/21.autograd/test_user_grad.py
Labels: bug
