Repository roastduck/FreeTensor, pull requests merged in 2024-04, with the labels that each got.

#605 Refactor `Lazy`
  include/lazy.h
  include/pass/sink_var.h
Labels: compiler performance

#606 Check incorrect `x: ft.Var[...]` where `x` is not a parameter
  python/freetensor/core/frontend.py
  python/freetensor/core/staging.py
  test/21.autograd/test_tape.py
  test/30.schedule/test_fuse.py
  test/40.codegen/gpu/test_gpu.py
  test/40.codegen/gpu/test_gpu_sync.py
  test/50.frontend/test_error_report.py
Labels: enhancement, productivity

#607 [CI] Upgrade CodeQL to v3
  .github/workflows/codeql.yml
Labels: dependencies

#608 Support `for` `in` a tensor + disable iterator synthesized by Python
  python/freetensor/core/expr.py
  python/freetensor/core/frontend.py
  python/freetensor/core/staging.py
  test/50.frontend/test_transformer_basic.py
Labels: enhancement, productivity

#611 Reject indexing into a scalar
  python/freetensor/core/expr.py
  test/00.hello_world/test_basic.py
  test/20.pass/test_prop_one_time_use.py
  test/20.pass/test_remove_cyclic_assign.py
  test/20.pass/test_remove_writes.py
  test/20.pass/test_scalar_prop_const.py
  test/40.codegen/gpu/test_gpu.py
Labels: bug

#615 Fix for different values of `nwarps` in CUTLASS micro kernel
  src/schedule/lower_cutlass_micro_block.cc
  test/70.program/test_program_with_micro_kernel.py
Labels: bug
